In [15]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,classification_report



In [16]:
# Load dataset
df=pd.read_csv('/boot/dataset/marital status.csv')
print("your total dataset null value is ",df.isnull().sum())


your total dataset null value is  age       0
status    1
dtype: int64


In [17]:
# Exploratory Data Analysis (EDA)
print(df.info())
print(df.describe())
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   age     18 non-null     int64  
 1   status  17 non-null     float64
dtypes: float64(1), int64(1)
memory usage: 420.0 bytes
None
             age     status
count  18.000000  17.000000
mean   24.555556   0.411765
std     5.648761   0.507300
min    16.000000   0.000000
25%    20.250000   0.000000
50%    24.000000   0.000000
75%    28.750000   1.000000
max    34.000000   1.000000
age       0
status    1
dtype: int64


In [18]:
# Handling missing values
mode=df['status'].mode()[0]
df['status']=df.status.fillna(mode)
df


age  status
0    21     0.0
1    33     1.0
2    24     0.0
3    28     1.0
4    17     0.0
5    33     1.0
6    23     0.0
7    30     1.0
8    19     0.0
9    22     0.0
10   26     0.0
11   20     0.0
12   24     0.0
13   34     1.0
14   29     1.0
15   16     0.0
16   18     0.0
17   25     1.0

In [19]:
# Splitting into training and testing sets
x=df['age'].values.reshape(-1,1)
y=df['status']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1,stratify=y)


In [20]:
# Model Training
logisreg=LogisticRegression()
logisreg.fit(x_train,y_train)
y_pred=logisreg.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)
print("your accuracy is ",accuracy)


your accuracy is  0.8333333333333334


In [21]:
# Predictions
sigmoidValue=logisreg.predict_proba(x_test)
print(y_pred)

print(sigmoidValue)

[0. 0. 0. 1. 0. 0.]
[[9.95085126e-01 4.91487445e-03]
 [9.65828465e-01 3.41715345e-02]
 [9.99310966e-01 6.89033853e-04]
 [3.55180496e-01 6.44819504e-01]
 [9.13497622e-01 8.65023778e-02]
 [9.99903753e-01 9.62466934e-05]]


In [22]:
#Model Evaluation
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[4 0]
 [1 1]]
